### ISSUE TITLE
Accommodate "timeless" type events that launch alongside existing events but never lock

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/sleepinnovate.org#110]
Some surveys only need to be done once, and we may not care about the timepoint when these surveys are completed. The idea is to shuffle around existing surveys (e.g. Biobank set) into "new" events that launch alongside existing events (Baseline, 3-mo, 6-mo, etc.), yet these new events do not "go away" (i.e. become unavailable) until the user completes these surveys. 

If they aren't filled out these timeless events would accrue in the background and still be available over the entire course of the project.

Note: We'll probably want to come up with some better naming scheme for all of this. I and others can help parse out which surveys would go in which new events.

**Comment by remomueller** [comment]
cc @mrueschman, should we move this to a future release?

**Comment by remomueller** [comment]
Removing from milestone
