### ISSUE TITLE
Time_of_day variables do not keep formatting from Slice when displayed through API

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/sleepinnovate.org#29]
E.g. we have a question about time going to bed, which omits seconds and uses "PM" by default

https://staging.partners.org/tryslice.io/projects/sleep-innovate/variables/16647

<img width="1011" alt="screen shot 2017-08-30 at 11 14 10 am" src="https://user-images.githubusercontent.com/707167/29879891-630f8cca-8d74-11e7-9f64-b09c2131ca84.png">

On sleepinnovate (staging), it displays like:

<img width="976" alt="screen shot 2017-08-30 at 11 13 41 am" src="https://user-images.githubusercontent.com/707167/29879871-538f76d4-8d74-11e7-94fe-1b6d6441ce23.png">

**Comment by remomueller** [comment]
The removal of seconds was not implemented (good catch), however the AM/PM default should be working, I'll have to see why it isn't.
