### ISSUE TITLE
Subject code creation template

### ISSUE THREAD

**Issue by remomueller** [sleepepi/sleepinnovate.org#3]
cc @mrueschman, thoughts on a subject code template?

Ideas:
`S%05d` => "S00001"
`SI%05d` => "SI00001"
`INN%05d` => "INN00001"

**Comment by mrueschman** [comment]
Agreed "SI" isn't ideal because of I/1.

No strong preference on the other options. "INN*" since that's the differentiating part of the project name? Everything else we have is "Sleep" ("S").

**Comment by remomueller** [comment]
OK, in that case I'll make it `INN%05d`, giving us results like `INN00001`, `INN02407`, etc.

**Comment by remomueller** [comment]
Closed in 09361b97b496f315c54361d0b49c57f9c4cb5998.
