### ISSUE TITLE
Ranges are not shown to users filling out survey when they try to save something out of range

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/sleepinnovate.org#30]
<img width="1087" alt="screen shot 2017-08-30 at 11 15 47 am" src="https://user-images.githubusercontent.com/707167/29880083-e7cceca0-8d74-11e7-9f0a-641fa7588805.png">

The user would be left wondering, "What is the specified range?".

**Comment by remomueller** [comment]
Please add this to either the question itself or the field note on the variable.

**Comment by mrueschman** [comment]
Is this not technically feasible? I would elect to not have ranges instead of confuse participants by showing them straightaway. The range should be obscured from the participant and is only intended to be seen/shown in rare cases of mistaken data entry.

In the case where it's not feasible (technically or otherwise), I will request it be added as an agenda item for next week to discuss a workaround.

**Comment by remomueller** [comment]
The responses back aren't going to be customizable for SleepINNOVATE as the API will be more generic as it will also affect MyApnea and other projects. I'm not adding this for the time until those are more clear how it affects multiple projects.

**Comment by mrueschman** [comment]
I don't foresee needing customizable error messaging between projects. Like the "Please enter a number below 750" (or some variation) seems fine for SleepINNOVATE, MyApnea, PATS caregivers, LOFT-HF participants, etc. I think a message like this falls more in line with the Google Material approach to errors that you've been going for elsewhere, right? Plus I think the message is sufficient/clear for data entry staff and research participants alike.

Could the validation messaging be revisited in Slice, which might later trickle down through projects using the API?

**Comment by remomueller** [comment]
Work will be done in Slice (should propagate over to SleepINNOVATE when fixed in the referenced issue https://github.com/remomueller/slice/issues/639)
