### ISSUE TITLE
Reloading profile page after validation error will cause page not found error

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/sleepinnovate.org#31]
If you make it here: https://staging.partners.org/sleepinnovate.org/profile/complete

Then click "Finish enrollment" with the fields incomplete, the validation errors show up and the URL changes from "profile/complete" to "profile/profile". If you then reload (at "profile/profile") you get an error page, presumably because this path isn't valid.

The same sort of thing happens at the sign-up page, which will transform from "/join" to "/" (the root) after validation errors. (Reloading in this case just sends you back to the hompage.)

**Comment by remomueller** [comment]
Good catch, thanks. The "join" to "root" one will be difficult as it's a devise default to do that.
