### ISSUE TITLE
Consent to be moved ahead of user registration

### ISSUE THREAD

**Issue by remomueller** [sleepepi/sleepinnovate.org#32]
Due to project requirements the consent is to be done before the registration

- [x] Store consent in cookie with time of consent
- [x] Admins should be "unconsented" if they sign up through this new process as there will no longer be a way to have them sign up without consenting (or at least removed from exports).
- [x] Remove signature
- [ ] ~~Consent and Welcome email should be combined as they are one thing now.~~ Moved to #39.

**Comment by remomueller** [comment]
cc @mrueschman let me know if I missed anything in this rework of the sign up flow.

**Comment by mrueschman** [comment]
Looks good to me.
