### ISSUE TITLE
Add information about email and password setting to notification after sign-up

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/sleepinnovate.org#38]

**Comment by remomueller** [comment]
Assigning you for the moment until text/copy is added to issue, thanks!

**Comment by mrueschman** [comment]
"Thanks for joining! Check your email for further instructions."

"Welcome to the study! Please check your email to complete registration."

"Welcome to the study! We sent an email with additional instructions."

Any preference(s)? Some combination?

Wasn't sure what a sort of de facto "max" length of notifications was.

**Comment by remomueller** [comment]
Maybe a combination: "Welcome to the study! Check your email to complete registration." I think the length should fit, but it also displays fairly quickly, and most people will probably miss it. Another thought (like you mentioned) would be to put the "finish registration to access TMB and Biobank" in the respective boxes as well.

**Comment by mrueschman** [comment]
That sounds good to me. I counted in my head and it seems like the notification shows for around 5 seconds, which I think should give most people enough time to read.

I imagine we'll talk more about the "grayed out" parts again at some point, so I'll keep that text in mind as well.
