### ISSUE TITLE
Consider moving wording from consent email to welcome email

### ISSUE THREAD

**Issue by remomueller** [sleepepi/sleepinnovate.org#39]

**Comment by mrueschman** [comment]
Just rolled around to this since you're doing 2.0. Is it too cheeky to add this bit as a "PS." to the welcome email?

```
You can download a copy of the consent through the link below:

View consent
```

Also, minor note, maybe change Welcome email wording to say "Please login and create a password" (not "create a new password")?

**Comment by remomueller** [comment]
Well, you don't login to create the password, you create it in order to login... Also, Ellen is taking a look at this as well in terms of combining the two.

**Comment by mrueschman** [comment]
I was going by the current wording - "new" seemed unnecessary. Something like, "Please create a password through the link below", might be more apt overall.

Another option for consent wording might be:

> Welcome to the SleepINNOVATE portal! We truly value your support and thank you for your interest. Your participation will help us better understand how sleep influences health and well-being and hopefully improve sleep healthcare.

Add another sentence..

> Welcome to the SleepINNOVATE portal! We truly value your support and thank you for your interest. Your participation will help us better understand how sleep influences health and well-being and hopefully improve sleep healthcare. We recommend you download and keep a copy of the consent for your records.

(download and onward could be linked)

**Comment by remomueller** [comment]
Is "onward" a typo? don't know where the second link should be placed, thanks!

**Comment by mrueschman** [comment]
Sorry, meant "download" and the rest of the sentence could be linked. Though on second thought, maybe only the "download and keep a copy of the consent" piece should be linked?

**Comment by remomueller** [comment]
Final question, should the "download" link directly link the PDF or simply the consent page? https://sleepinnovate/consent vs https://sleepinnovate/consent.pdf

**Comment by remomueller** [comment]
![screen shot 2017-09-13 at 10 17 11 am](https://user-images.githubusercontent.com/316479/30393522-62f285a6-988e-11e7-8996-13138cbf3c78.png)

**Comment by remomueller** [comment]
Thanks!
