### ISSUE TITLE
Make parking voucher text larger

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/sleepinnovate.org#41]
- [x] Make the text below "Brain Quizzes" panel larger.

**Edit:** Upon further discussion with Rachel, let's also try the following:

- [x] Change text to "Redeem your parking voucher"
- [ ] Add red car icon next to text. I think the red might stand out!

**Comment by remomueller** [comment]
Red doesn't fit with the color scheme, plus it's not a color that "stands out" in terms of accessibility either. Would the standard link color be fine here? (Plus we currently already have three competing items for the user's attention on top of this)

**Comment by remomueller** [comment]
![screen shot 2017-09-13 at 1 42 48 pm](https://user-images.githubusercontent.com/316479/30392019-7846255c-9889-11e7-978a-1012154e4e08.png)

Or even like this (no extra color)

**Comment by mrueschman** [comment]
Ha, color-less is fine. I suggested red because it's the classic car color and because it would stand out (like a sore thumb) in the current scheme!

**Comment by remomueller** [comment]
Alright, thanks! Closing issue.
