### ISSUE TITLE
Add additional helper text to password creation/change page to indicate password requirements

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/sleepinnovate.org#43]
Indicate to users the requirements prior to submitting an insufficiently secure password.

<img width="426" alt="screen shot 2017-09-07 at 9 02 27 pm" src="https://user-images.githubusercontent.com/707167/30191618-f3bad634-940f-11e7-9b19-43ced6f60933.png">

On a side note, is it possible to have the password setting page (linked from the email) say "Create your password" instead of "Change your password"? The link in the email reads "Create your password". My literal self thinks, "How can I change my password when I never created one in the first place!"

**Comment by remomueller** [comment]
@mrueschman, I changed it to now say "Set your password" for the title, and "Update my password" for the button. Thoughts?

**Comment by mrueschman** [comment]
That change sounds good. I'll keep it in mind to look at during the next go-around of testing.
