### ISSUE TITLE
Add Pledge page

### ISSUE THREAD

**Issue by remomueller** [sleepepi/sleepinnovate.org#6]
- [x] Create page based on Rachel S's design
- [x] Check if text needs change from "and can read English" to "who can read English"?

**Comment by remomueller** [comment]
@mrueschman Should the new pledge page replace the "About" page, or are those two still different?

**Comment by mrueschman** [comment]
Different!

**Comment by remomueller** [comment]
Ok, I'll make an issue to redo the about page then as well (it also needs to point to pledge as starting point)
