### ISSUE TITLE
Add line about longitudinal followup (3month 6month) to landing page text

### ISSUE THREAD

**Issue by remomueller** [sleepepi/sleepinnovate.org#68]

**Comment by remomueller** [comment]
cc @mrueschman: Can you work with Ellen to get the text for this, I think only a sentence or so needs to be added to the landing page for this.

**Comment by mrueschman** [comment]
Yes, will keep this in mind.

**Comment by mrueschman** [comment]
Add "We plan to do this by contacting you at least once a year by email." sentence after:

> What will happen in this research study? We will ask you to complete surveys about yourself and your health, general functioning and sleep habits. In addition, we will ask you to take brain quizzes to help us understand the relationship between sleep and brain functions.
