### ISSUE TITLE
Update "Withdrawn from Study" page

### ISSUE THREAD

**Issue by remomueller** [sleepepi/sleepinnovate.org#7]

**Comment by remomueller** [comment]
cc @mrueschman, moving this to followup release since it's not critical for an initial release.

**Comment by remomueller** [comment]
Assigning you to collect text/copy for changes.

**Comment by mrueschman** [comment]
Something like this, perhaps? With "consent" and "contact us" being links.

**When clicking "I Do Not Consent":**

Thank you for considering to participate in SleepINNOVATE. 

If you change your mind, please review the consent again. If you have any questions, please contact us.

**When Withdrawing from Settings page (post-consent):**

Withdrawn from Study
You withdrew from SleepINNOVATE on September 9th, 2017. Thank you for participating. 

If you would like to rejoin the study, please review the consent again. If you have any questions, please contact us.
