### ISSUE TITLE
Style date variables to use dropdowns for Month, Day, Year

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/sleepinnovate.org#72]
Similar look to how DOB is entered during sign-up. Dropdowns help avoid issues with accessing numerical keyboard, entering crazy values/symbols, etc.

**Comment by remomueller** [comment]
SleepINNOVATE surveys don't appear to have any date variables: https://tryslice.io/projects/sleep-innovate/variables?variable_type=date

**Comment by mrueschman** [comment]
That's true - we phased them out in favor of categorical variables like, "How long ago were you diagnosed?" instead of "When were you diagnosed? <exact date!>"

Guess this doesn't apply to SleepINNOVATE at this point, though it might come up again with a future study that uses the Slice API. We could close this issue and re-open for a different project if it crops up down the line?

**Comment by remomueller** [comment]
Sure, we can reopen when it comes up again, probably on a different project.
