### ISSUE TITLE
Add "study progress" timeline/bar to dashboard

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/sleepinnovate.org#75]
E.g.

Circles separated by dashes that go Baseline, 3-mo, 6-mo, 12-mo, 24-mo, with future events grayed out and the current (active) event highlighted. Then the meter/bar can fill in as participant progresses.

**Comment by remomueller** [comment]
Closed by 0ebf1b77b3414e3e1324ae23158f6ef0c41574ea
