### ISSUE TITLE
Add default "Please select an answer" type text to dropdowns

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/sleepinnovate.org#79]
Currently blank: ![image](https://user-images.githubusercontent.com/707167/32549850-efc1e90e-c458-11e7-9292-22582ac648fc.png)

Slice has "Select an Option" text by default: 
![image](https://user-images.githubusercontent.com/707167/32549877-0a3db768-c459-11e7-99d8-5d5e2b8e4cf7.png)

**Comment by remomueller** [comment]
@mrueschman I made this more concise and changed it to "Select answer". Reference: https://material.io/guidelines/style/writing.html#writing-language
