### ISSUE TITLE
Compute TMB completion differently

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/sleepinnovate.org#87]
Currently using # of batteries, which might exceed the actual number of tasks. That is, some tasks have multiple battery-test combinations.

![image](https://user-images.githubusercontent.com/707167/33949366-62067980-dff7-11e7-92cb-9789fc5aa41e.png)

**Comment by remomueller** [comment]
Good catch, thanks!

**Comment by remomueller** [comment]
- [ ] Add unique index to "event", "battery", "test"
- [ ] Count by number of batteries available (7), instead of tests (9)

**Comment by remomueller** [comment]
This is actually working as expected, closing issue.
